### ISSUE TITLE
Thumbnail images

### ISSUE THREAD

**Issue by laurenengelwilder** [psrc/data-portal-tools#85]
I'd like to include thumbnail images for data, so is there a way to include that in the scripting so it's not deleted when data is republished?

**Comment by christopeak** [comment]
I think republishing a layer currently does preserve the thumbnail.  The reason they were almost all wiped recently was that in order to rename all the layers with capitals I had to delete and then publish them again as new.  I just tested republishing a layer and the thumbnail remained as it was.  Closing this for now but feel free to re-open if you continue to see otherwise.
